tags:
- name: customers
  description: customers API

paths:
# [GET] customers
  /customers:
    get:
      tags:
      - customers
      summary: Find All Customers
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] customers
    post:
      tags:
      - customers
      summary: Add Customer
      parameters:
      - name: body
        in: body
        description: customer Data
        required: true
        schema:
          $ref: '#/definitions/customers'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] customers/id
  /customers/{id}:
    get:
      tags:
      - customers
      summary: Find Customer By Id
      parameters:
      - name: id
        in: path
        description: Customer Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] customers/id
    put:
      tags:
      - customers
      summary: Update Customer By Id
      parameters:
      - name: id
        in: path
        description: customer Id
        required: true
        type: integer
      - name: body
        in: body
        description: customer Data
        required: true
        schema:
          $ref: '#/definitions/customers'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] customers/id
    delete:
      tags:
      - customers
      summary: Delete Customer By Id
      parameters:
      - name: id
        in: path
        description: customer Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  customers:
    type: object
    required:
        - email
        - password
    properties:
      id:
        type: integer
        description: customer Id
      email:
        type: string
        description: customer Email
      password:
        type: string
        description: customer Password

schemes:
 - https
 - http
